collections:
  - name: "community.general"
    version: ">=11.0.0,<12.0.0"
  - name: "community.proxmox"
    version: ">=1.0.0,<2.0.0"
  - name: "netbox.netbox"
    version: ">=3.21.0,<4.0.0"
  - name: "community.windows"
    version: ">=3.0.0,<4.0.0"
  - name: ansible.windows
    version: ">=3.2.0,<4.0.0"
  - name: ansible.posix
    version: ">=2.0.0,<3.0.0"
  - name: ansible.utils
    version: ">=6.0.0,<7.0.0"
