name: ðŸœ Bug Report
description: ðŸœ Bug Report
labels:
  - bug
type: bug
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only!
  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing here, to communicate to the
        maintainers. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.
  - type: input
    attributes:
      label: What was the last working version of the Fluffy Execution Environment?
      placeholder: fluffy-ee:stable
      description: >
        If known, otherwise leave blank.
  - type: dropdown
    validations:
      required: true
    attributes:
      label: How are you using the EE?
      options:
        - AWX
        - Ansible Standalone
        - Ansible Automation Platform
        - Other
  - type: input
    id: module_name
    attributes:
      label: Integration causing the issue
      description: >
        The fully qualified name of the module, for example `ansible.builtin.debug`
  - type: input
    id: module_link
    attributes:
      label: Link to module documentation or repository.
      placeholder: "https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html"
      description: |
        Providing a link the documentation or repository helps us categorize the issue and might speed up the
        investigation, while also providing a useful reference for others.

  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    attributes:
      label: Diagnostics information
      placeholder: "drag-and-drop the diagnostics data file here (do not copy-and-paste the content)"
      description: >-
        Many integrations provide the ability to [download diagnostic data](https://www.home-assistant.io/docs/configuration/troubleshooting/#debug-logs-and-diagnostics).

        **It would really help if you could download the diagnostics data for the device you are having issues with,
        and <ins>drag-and-drop that file into the textbox below.</ins>**

        It generally allows pinpointing defects and thus resolving issues faster.
  - type: textarea
    attributes:
      label: Example Playbook
      description: |
        If applicable, please provide an example playbook that can help reproduce this problem.
      render: yaml
  - type: textarea
    attributes:
      label: Anything in the logs that might be useful for us?
      description: For example, error message, or stack traces.
      render: text
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
