---
name: 🎭 - User Story
description: This is the default template for user stories
title: 🎭 -
labels: new
projects:
  - forristalorg/projects/1
body:
  # MARKDOWN:
  - type: markdown
    attributes:
      value: |
        Intiatives contain Epics. 

        Epics contain Stories.

  # DROPDOWN:
  - type: dropdown
    id: story_type
    attributes:
      label: What kind of user story is this?
      options:
        - Initiative
        - Epic
        - Story
    validations:
      required: true

  - type: textarea
    id: story
    attributes:
      label: Story
      value: |
        As a ...
        We want to ...
        So we can ...
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      value: |
        - [ ] Item 1
        - [ ] Item 2
      render: Markdown
    validations:
      required: true

  - type: checkboxes
    id: sprint_ready
    attributes:
      label: Sprint Ready Checklist
      options:
        - label: Acceptance criteria defined
          required: true
        - label: Team understands acceptance criteria
          required: false
        - label: Team has defined solution / steps to satisfy acceptance criteria
          required: false
        - label: Acceptance criteria is verifiable / testable
          required: false
        - label: External / 3rd party dependencies are identified
          required: false

  - type: textarea
    id: related_items
    attributes:
      label: Related Items
      description: Please link any related items here
      placeholder: |
        You can reference issues by their id, for example:
        #4 - Issue 4

  - type: textarea
    id: artifacts
    attributes:
      label: Artifacts
      description: Please attach any related artifacts here.
      placeholder: |
        Links to documentation, screenshots, etc...
